version: '3'

networks:
  pigpig_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 168.171.10.0/24

services:
  pigpig-master:
    image: 127.0.0.1:5050/notone/pigpig-arm64:v1.0.0-1-gd0663bf
    container_name: pigpig-master
    command: pigpig -c /etc/pigpig/pigpig.yaml --redis.host=168.171.10.5 --etcd.endpoints=168.171.10.4:2379 --server.cluster.enable=true --server.cluster.name=my_cluster --server.cluster.role=master -m=true
    ports:
      - 8088:8088
      - 8443:8443
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.2
    restart: unless-stopped
    volumes:
#      - configs/pigpig_container.yaml:/etc/pigpig/pigpig.yaml:ro
      - type: bind
        source: ./configs/pigpig_container.yaml
        target: /etc/pigpig/pigpig.yaml
        volume:
          nocopy: true

  pigpig-slave1:
    image: 127.0.0.1:5050/notone/pigpig-arm64:v1.0.0-1-gd0663bf
    container_name: pigpig-slave1
    command: pigpig -c /etc/pigpig/pigpig.yaml --redis.host=168.171.10.5 --etcd.endpoints=168.171.10.4:2379 --server.cluster.enable=true --server.cluster.name=my_cluster --server.cluster.role=slave
    ports:
      - 9088:8088
      - 9443:8443
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.3
    restart: unless-stopped
    volumes:
#      - configs/pigpig_container.yaml:/etc/pigpig/pigpig.yaml:ro
      - type: bind
        source: ./configs/pigpig_container.yaml
        target: /etc/pigpig/pigpig.yaml
        volume:
          nocopy: true

  pigpig-etcd:
    image: quay.io/coreos/etcd
    container_name: pigpig-etcd
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "5566:2379"
      - "5567:2380"
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.4
    environment:
      - ETCDCTL_API=3
    restart: unless-stopped

  pigpig-redis:
    image: library/redis:5.0
    container_name: pigpig-redis
    command: redis-server --bind 0.0.0.0
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.5
    restart: unless-stopped

