# Copyright 2022 NotOne Lv <aiphalv0010@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

version: '3'

networks:
  pigpig_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 168.171.10.0/24

services:

  pigpig-etcd:
    image: quay.io/coreos/etcd
    container_name: pigpig-etcd
    command: etcd -name etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380
    ports:
      - "5566:2379"
      - "5567:2380"
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.4
        aliases:
          - etcd
    environment:
      - ETCDCTL_API=3
    restart: unless-stopped

  pigpig-redis:
    image: library/redis:5.0
    container_name: pigpig-redis
    command: redis-server --bind 0.0.0.0
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.5
        aliases:
          - redis
    restart: unless-stopped

  pigpig-master:
    image: 127.0.0.1:5050/notone/pigpig-arm64:v1.0.0-5-g080201b
    container_name: pigpig-master
    command: -c /etc/pigpig/pigpig.yaml --server.cluster.enable=true --server.cluster.name=my_cluster --server.cluster.role=master -m=true --log.level=info
    ports:
      - 8088:8088
      - 8443:8443
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.2
    restart: unless-stopped
    volumes:
      #      - configs/pigpig_container.yaml:/etc/pigpig/pigpig.yaml:ro
      - type: bind
        source: ./configs/pigpig_container.yaml
        target: /etc/pigpig/pigpig.yaml
        volume:
          nocopy: true
      - type: bind
        source: ./configs/cert
        target: /etc/cert
        volume:
          nocopy: true
    depends_on:
      - pigpig-etcd
      - pigpig-redis

  pigpig-slave1:
    image: 127.0.0.1:5050/notone/pigpig-arm64:v1.0.0-5-g080201b
    container_name: pigpig-slave1
    command: -c /etc/pigpig/pigpig.yaml --server.cluster.enable=true --server.cluster.name=my_cluster --server.cluster.role=slave --log.level=info
    ports:
      - 9088:8088
      - 9443:8443
    networks:
      pigpig_net:
        ipv4_address: 168.171.10.3
    restart: unless-stopped
    volumes:
      #      - configs/pigpig_container.yaml:/etc/pigpig/pigpig.yaml:ro
      - type: bind
        source: ./configs/pigpig_container.yaml
        target: /etc/pigpig/pigpig.yaml
        volume:
          nocopy: true
      - type: bind
        source: ./configs/cert
        target: /etc/cert
        volume:
          nocopy: true
    depends_on:
      - pigpig-etcd
      - pigpig-redis
      - pigpig-master
